### ISSUE TITLE
Too much "zoom out" prevents a file from opening

### ISSUE THREAD

**Issue by vorth** [vorth/vzome-desktop#8]
The “zoom” slider has a fixed bound, in terms of how far out you can zoom, but the scroll wheel on a mouse (over the main view) will let you zoom much farther out.  The problem occurs when you are zoomed that far out, and you save the file.  When vZome tries to open it, it naively tries to set the zoom slider to that value, without checking it against the bounds.  This will be a simple fix.

Until the fix is available, as a user you can correct the problem yourself, simply by editing the problematic file in a text editor, and replacing the “ViewModel” element.  Here is the default ViewModel, as extracted from an empty vZome document with no view changes applied.

    <ViewModel distance="108.73126983642578" far="217.46253967285156" near="0.2718281786416199" parallel="false" stereoAngle="0.0" width="48.9290714263916">
      <LookAtPoint x="0.0" y="0.0" z="0.0"/>
      <UpDirection x="0.0" y="1.0" z="0.0"/>
      <LookDirection x="0.0" y="0.0" z="-1.0"/>
    </ViewModel>

You can use this value to replace the out-of-scale ViewModel in your files.  Don’t try to change the distance value, etc. manually… replace the entire ViewModel element (all five lines).

Make sure you save a backup of any vZome file you intend to “fix” in this way!

**Comment by david-hall** [comment]
It seems like it would be a simple fix to have the code that parses the
vZome file check the distance attribute and if it is outside the slider's
range then use the nearest valid slider value instead of the value in the
file. The actual zoom level could then automatically be based on the slider
position, or, with a bit more work, it could still use the value in the
file, just as though it had been adjusted by the wheel mouse. In the former
case, the zoom wouldn't be the same as when it was saved, but at least the
file would load without a problem. Readjusting the zoom after loading the
file would be much preferable to cut-and-pasting the vZome file. I realize
that I'm probably the only one with the problem, but it seems like such a
simple fix that it should eventually be incorporated. If it's as simple as
I think it is, I'll be glad to fix it after the more pressing issues are
done. Let me know if I'm missing something significant. In the meanwhile,
thanks for the fix so I can load the file that was giving me problems.

**Comment by vorth** [comment]
Thanks, David.  I have the fix already, just adding a max and min call anytime when adjusting the slider model.  This is essentially the same as your suggestion, but more decoupled from file loading, so it will protect from future code changes that might set an out-of-range magnification.

**Comment by david-hall** [comment]
Even better!
